### ISSUE TITLE
`Type.Void` / `Type.Undefined` throws `FST_ERR_SCH_SERIALIZATION_BUILD` since typebox 0.30.0

### ISSUE THREAD

**Issue by Amphaal** [fastify/fastify-type-provider-typebox#109]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

3.5.0

### Node.js version

18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5.2

### Description

https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md#Extended-Type-Representation-Change might have produced this regression.

Below example will produce an error since 0.30.0 (0.29.6 was fine, i'm using 0.31.16) : 
`FastifyError [Error]: Failed building the serialization schema for GET: /test, due to error schema is invalid: data/type must be equal to one of the allowed values `

### Steps to Reproduce

```
import { type TypeBoxTypeProvider, Type } from '@fastify/type-provider-typebox'
import fastify from 'fastify'

async function main () {
  const webServer = fastify().withTypeProvider<TypeBoxTypeProvider>()

  webServer.route({
    method: 'GET',
    url: '/test',
    handler: () => { },
    schema: {
      response: {
        200: Type.Void()
      }
    }
  })

  //
  await webServer.ready()
}

//
main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })

```

### Expected Behavior

`void` should still be considered a valid validation value by `ajv`, as it describes an absence of returned value, which is not very user-friendly API-wise, but still useful for mocking.

**Comment by Amphaal** [comment]
Just noticed `Type.Undefined()` has the same problem.

**Comment by sinclairzx81** [comment]
@Amphaal Hiya,

Unfortunately, Ajv never actually supported these types as Json can't represent `void` or `undefined` as values. Because these values can't be represented, Json Schema doesn't support validation of them (and it's difficult to implement work arounds in Ajv to make these types validate at all)

Previous to 0.30.0, TypeBox made some concessions to try and support these types through `addKeyword` configuration (and custom AJv schematics), however these representations were only partially workable, and a bit too tied to some of the behaviors of Ajv (when [other](https://github.com/hyperjump-io/json-schema) validators exist), so the decision was made to simplify the TB schematics and draw a greater distinction between Json serializable data, and JavaScript native data types.

Essentially, the general recommendation moving forward is to use only types prefixed with the `[Json]` doc comment, and reserve those types prefixed with `[JavaScript]` for TypeBox's TypeCompiler and Value modules (as these are written to validate data structures above and beyond Json Schema).

You can configure Fastify to use the TypeCompiler [here](https://github.com/fastify/fastify-type-provider-typebox#type-compiler) which would support validation of these types, but would recommend keeping on specification if you can (so using Ajv with Json supported types)

Hope this brings some insights.
Cheers
S

**Comment by Amphaal** [comment]
> @Amphaal Hiya,
> 
> Unfortunately, Ajv never actually supported these types as Json can't represent `void` or `undefined` as values. Because these values can't be represented, Json Schema doesn't support validation of them (and it's difficult to implement work arounds in Ajv to make these types validate at all)
> 
> Previous to 0.30.0, TypeBox made some concessions to try and support these types through `addKeyword` configuration (and custom AJv schematics), however these representations were only partially workable, and a bit too tied to some of the behaviors of Ajv (when [other](https://github.com/hyperjump-io/json-schema) validators exist), so the decision was made to simplify the TB schematics and draw a greater distinction between Json serializable data, and JavaScript native data types.
> 
> Essentially, the general recommendation moving forward is to use only types prefixed with the `[Json]` doc comment, and reserve those types prefixed with `[JavaScript]` for TypeBox's TypeCompiler and Value modules (as these are written to validate data structures above and beyond Json Schema).
> 
> You can configure Fastify to use the TypeCompiler [here](https://github.com/fastify/fastify-type-provider-typebox#type-compiler) which would support validation of these types, but would recommend keeping on specification if you can (so using Ajv with Json supported types)
> 
> Hope this brings some insights. Cheers S

Many thanks for the detailed explanation, much clearer to me 🙏
