### ISSUE TITLE
Update TypeBox to 0.33.4

### ISSUE THREAD

**Issue by nikeee** [fastify/fastify-type-provider-typebox#161]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm getting a peer-dep issue:
```
npm error Could not resolve dependency:
npm error peer @sinclair/typebox@">=0.26 <=0.32" from @fastify/type-provider-typebox@4.0.0
npm error node_modules/@fastify/type-provider-typebox
npm error   @fastify/type-provider-typebox@"^4.0.0" from the root project
```

Don't know wether there are breaking changes. Is this open for contribution?

**Comment by kibertoad** [comment]
yes, of course! go for it

**Comment by nickfla1** [comment]
The only issue I can see with the latest version is that `RegExp` si broken.
This is the MRE repo: https://github.com/nickfla1/fustily-swagger-typebox-regexp-bug, initially I thought it was related to `@fustily/swagger` but turns out it happens regardless of that plugin being used.

I'm also available to contribute if you @nikeee don't find the time to

**Comment by nikeee** [comment]
@nickfla1 feel free; to do so. I'm currently short on time. Thank you!
