### ISSUE TITLE
support typebox v33?

### ISSUE THREAD

**Issue by jessekrubin** [fastify/fastify-type-provider-typebox#180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Is there any reason why the typebox peer-dependency is not set to allow version 33? Is there an incompatibility?

**Comment by climba03003** [comment]
Each minor version of `typebox` may introduce breakage, it only need someone to test it before changing the supporting version for each new version of `typebox`.
If you sure it can be supported, feel free to submit PR.

**Comment by jessekrubin** [comment]
@climba03003 Thanks. Will do!

**Comment by Kenneth-Sills** [comment]
Reviewing the release notes, I do see some breaking changes. Sinclair has phenomenal "internal" documentation here, really easy to understand what broke:

- [**Version 33:**](https://github.com/sinclairzx81/typebox/pull/941)
	- Changes the default `TypeSystemPolicy.InstanceMode` to `default` (from `clone`). This is a big boon for performance, but has implications for edge-case users that bind some Typebox schema to a variable, use it in another Typebox type, then modify the original definition.
- [**Version 34:**](https://github.com/sinclairzx81/typebox/pull/1069)
	- `Ref` has been demoted to a constant string, no longer able to reference Typebox schemas, to be replaced by the new opt-in [Modules](https://github.com/sinclairzx81/typebox/blob/010d1818ba7c1ae7f3973ead35dfc6946eac6447/readme.md#types-modules). However, as of `0.34.7` the prior implementation was brought back and marked `@deprecated`.
	- Subsequently, `Deref` was removed as it's useless now.
	- Unrelated to that, the deprecated `Strict` was removed as it's no longer necessary or widely used.

No changes should affect the code in this project. Since we use a peer dependency and aren't dropping any support down, anyone with this plugin already installed will be unaffected by the bump. New projects would get the newest version, of course, but that's not a break. As such, a minor release bump should be good.

PR #196 has been submitted, so we just need to wait until a maintainer like @Fdawgs has some free time available to review and schedule a new release.
